/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package walk;

import java.util.Arrays;
import java.util.Scanner;

// import java.util.Arrays;

public class App {

	public static void main(
		String[] args
	) {
		Car myCar = new Car();
		myCar.kind = "Sonata";
		myCar.color = "white";
		myCar.year = 2015;

		myCar.run();
		myCar.speedUp();

		Dog happy;
		happy = new Dog();
		happy.name = "Happy";

		Dog lofi = happy;

		lofi.age = 3;

		System.out.printf(
			"my dog's name is %s\n",
			happy.name
		);
		System.out.printf(
			"and %d years old\n",
			lofi.age
		);

		Student s1 = new Student(
			// 1,
			// "name",
			// new Score(24, 24)
		);
		s1.setName("Abiria");
		s1.setScore(new Score(5, 5));

		Student s2 = new Student();
		s2.setName("David");
		s2.setScore(new Score(34, 34));

		s1.printStudent();
		s2.printStudent();

		s1.incScore(new Score(10, 10));
		s2.incScore(
			new Score(-10, -10)
		);

		s1.printStudent();
		s2.printStudent();

		Point p = new Point(123, 456);
		p.print();

		PersonInfo p1 = new PersonInfo();
		p1.printAll();

		PersonInfo p2 = new PersonInfo(
			"Alice",
			10,
			115.9
		);

		p2.printAll();

		System.out.println(
			PersonInfo.count
		);

		Circle c1 = new Circle(10.0);
		Circle c2 = new Circle(100.0);

		System.out.println(
			c1.perimeter()
		);
		System.out.println(c1.area());
		System.out.println(
			Circle.Tau()
		);

		Book b = new Book(
			"Harry Potter and the Library",
			4576
		);
		b.printBook();
		// b.price = 39287;

		b.setPrice(1234567889);
		b.printBook();

		Data d1 = new Data();
		d1.y = 7832465;
		d1.z = 453786;

		Point np1 = new Point(10, 20);
		Point np2 = new Point(30, 40);

		Point np3 = Point.add(np1, np2);
		np3.print();

		Student[] students = new Student[5];
		students[0] = new Student();
		students[1] = new Student();
		students[2] = new Student();
		students[3] = new Student();
		students[4] = new Student();

		for (Student student : students) {
			student.setScore(
				new Score(10, 20)
			);
		}

		for (Student student : students) {
			student.printStudent();
		}

		int[] arr = new int[10];
		arr =
			new int[] {
				10,
				20,
				30,
				40,
				50,
				60,
				70,
				80,
				90,
				100,
			};

		for (
			int i = 0;
			i < arr.length;
			i++
		) {
			System.out.println(arr[i]);
		}

		System.out.println(
			Arrays.toString(arr)
		);

		System.out.println(arr);

		int[] arr1 = { 1, 2, 3, 4 };
		int[] arr2 = { 10, 20, 30, 40 };

		System.arraycopy(
			arr1,
			0,
			arr2,
			2,
			2
		);

		System.out.println(
			Arrays.toString(arr2)
		);

		int[] arr3 = arr2;

		arr3[3] = 1234567890;

		System.out.println(
			Arrays.toString(arr2)
		);

		int[][] mdarr = new int[2][3];

		mdarr[0][0] = 0;
		mdarr[0][1] = 1;
		mdarr[0][2] = 2;
		mdarr[1][0] = 3;
		mdarr[1][1] = 4;
		mdarr[1][2] = 5;

		// System.out.println(
		// 	Arrays.toString(mdarr)
		// );
		double total = 0.0;

		for (int[] row : mdarr) {
			for (int item : row) {
				System.out.print(
					item + " "
				);
				total += item;
			}
			System.out.println();
		}

		System.out.println(
			String.format(
				"the average is: %f",
				total / mdarr.length
			)
		);

		char[] alphabet = {
			'A',
			'b',
			'i',
			'r',
			'i',
			'a',
		};

		for (char ch : alphabet) {
			System.out.print(ch);
		}

		Coin coin1 = new Coin(500, 4);
		Coin coin2 = new Coin(100, 43);
		Coin coin3 = new Coin(50, 44);
		Coin coin4 = new Coin(10, 123);

		Coin[] coins = {
			coin1,
			coin2,
			coin3,
			coin4,
		};

		Purse purse = new Purse(
			"Alice",
			coins
		);

		System.out.printf(
			"the number of each coin, in %s's purse\n",
			purse.getOwner()
		);

		int total_coins = 0;
		for (Coin coin : purse.getCoins()) {
			System.out.printf(
				"%d of %d won\n",
				coin.getCount(),
				coin.getValue()
			);
			total_coins +=
				coin.getValue() *
				coin.getCount();
		}

		System.out.println(
			String.format(
				"%s has totally %d won in her purse",
				purse.getOwner(),
				total_coins
			)
		);

		Person person = new Person(
			"Abiria",
			"010-4047-3142"
		);
		person.printPerson();

		InheritedStudent inheritedStudent = new InheritedStudent(
			"Kokoa",
			"010-4355-4524",
			436
		);

		inheritedStudent.printPerson();
		inheritedStudent.printStudent();

		Parent parent = new Parent(10);
		parent.show();
		parent.print();

		Child child = new Child(20);
		child.show();
		child.show("Abiria");
		child.print();
		child.check();
		child.printData();
		// child.z = 234867;

		final int cons;

		cons = 452;
		// cons = 4374;

		TheParent.main();

		System.out.println(
			child instanceof Child
		);
		System.out.println(
			child instanceof Parent
		);
		// System.out.println(
		// 	child instanceof Book
		// );
		TheCar.main();

		java.lang.String aim = "dh";
		java.lang.System.out.println(
			aim
		);

		Scanner scin = new java.util.Scanner(
			java.lang.System.in
		);
		java.lang.System.out.print(
			"Enter your name: "
		);
		System.out.println(
			scin.hasNext()
		);

		if (scin.hasNext()) {
			java.lang.String name = scin.next();
			java.lang.System.out.println(
				java.lang.String.format(
					"Hello, %s!" + name
				)
			);
		}

		newpkg.App.main();

		tree.main.Main.main();
		abstr.Main.main();

		// int dfasghdgfad = 123f;
		// System.out.println(dfasghdgfad);
		stl.Main.main();
		err.Main.main();
		io.Main.main();
		generics.Main.main();
		lambda.Main.main();
	}
}
